{
 "title": "Nginx",
 "description": "Nginx Web Server Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{job=\"nginx\"},instance)"
   },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Request Bytes by Status Code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Response 2XX / 5m",
   "type": "timeseries",
   "description": "Requests with 200 Status Code",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(filelogger_http_response_size_bytes{instance=~\"$instance\", status=~\"2..\"}[5m])",
     "legendFormat": "{{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "Total Response 200 Req. [24h]",
   "type": "bargauge",
   "description": "Total number of request in 24 hours for 200 response by nginx server",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(filelogger_http_response_size_bytes{instance=~\"$instance\", status=\"200\"}[24h])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Response 4XX / 5m",
   "type": "timeseries",
   "description": "Requests with 4XX Status Code",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(filelogger_http_response_size_bytes{instance=~\"$instance\", status=~\"4..\"}[5m])",
     "legendFormat": "{{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "Total Response 404 Req. [24h]",
   "type": "bargauge",
   "description": "Total number of request in 24 hours for 404 response from nginx server",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(filelogger_http_response_size_bytes{instance=~\"$instance\", status=\"404\"}[24h])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Response 3XX",
   "type": "timeseries",
   "description": "Requests with 3XX Status Code",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(filelogger_http_response_size_bytes{instance=~\"$instance\", status=~\"3..\"}[5m])",
     "legendFormat": "{{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "Response 5XX",
   "type": "timeseries",
   "description": "Requests with 5XX Status Code",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(filelogger_http_response_size_bytes{instance=~\"$instance\", status=~\"5..\"}[5m])",
     "legendFormat": "{{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "Total Request 503 Resonse",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(filelogger_http_response_size_bytes{instance=~\"$instance\", status=\"503\"}[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Nginx Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Accepted Connections",
   "type": "timeseries",
   "description": "The total number of accepted connections from clients since the nginx master process started. Note that reloading configurations or restarting worker processes will not reset this metric. If you terminate and restart the master process, you will reset the metric.\n\n",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_connections_accepted{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Writing Connections",
   "type": "timeseries",
   "description": "The current number of connections from clients where nginx is writing a response back to the client.\n",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nginx_connections_writing{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "description": "The current number of active (accepted) connections from clients. Includes all connections with the statuses Idle / Waiting, Reading, and Writing.",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Waiting Connections",
   "type": "timeseries",
   "description": "The current number of connections from clients that are in the Idle / Waiting state.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Handled Connections",
   "type": "timeseries",
   "description": "The total number of handled connections from clients since the nginx master process started. This will be lower than accepted only in cases where a connection is dropped before it is handled.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_connections_handled{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The total number of client requests since the nginx master process started. A request is an application-level (HTTP, etc.) event. It occurs when a client requests a resource via the application protocol. A single connection can (and often does) make many requests. So most of the time, there are more requests than accepted/handled connections.",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_http_requests_total{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reading Connections",
   "type": "stat",
   "description": "The current number of (accepted) connections from clients where nginx is reading the request. Measured at the time the status module was queried.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nginx_connections_reading{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}