keys:
  # Users
  - &users:
    - &christoph 47D61FEBCD86F3ECD2E3D68A83D074F348B2FD9D
  # Hosts
  - &hosts:
    - &phantasia age1kdmc7uwtgnghwyn4uzswdkc4ya3wvgk3egquejthvx99wyd2fpdqg9pkzp
    - &gallifrey age148f0u0ytpveuaq8xgeulnrm6l7fslc8gysk2uaf03tt9ejern3ys9vteg7
    - &medusa age1rcf425yjzkua5keaktw6s9rkjwx28vgkjm7evtt0m5s3lpyz9p6sr73k6j
    - &tuathaan age1qrvskael2jehwv8yg0f7f6tn5zd3rfez0ne7fzsqn0t5up58k9aqcegsdl
  # Home directories on non-nixos machines
  - &homes:
    - &jabsserver age1e332tl8qsuwpwp4xcqry9ktvdr3wdnqsmwmvgykme4w0463gs47s8aafe9
creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *phantasia
      - *gallifrey
      - *medusa
      - *tuathaan
      pgp:
      - *christoph
  - path_regex: hosts/gallifrey/secrets.ya?ml$
    key_groups:
    - age:
      - *gallifrey
      pgp:
      - *christoph
  - path_regex: hosts/medusa/kodi-secrets.ya?ml$
    key_groups:
    - age:
      - *medusa
      pgp:
      - *christoph
  - path_regex: home/christoph/jabsserver/secrets.ya?ml$
    key_groups:
    - age:
      - *jabsserver
      pgp:
      - *christoph
