keys:
  # Users
  - &users:
    - &christoph 47D61FEBCD86F3ECD2E3D68A83D074F348B2FD9D
  # Hosts
  - &hosts:
    - &phantasia age1kdmc7uwtgnghwyn4uzswdkc4ya3wvgk3egquejthvx99wyd2fpdqg9pkzp
    - &gallifrey age148f0u0ytpveuaq8xgeulnrm6l7fslc8gysk2uaf03tt9ejern3ys9vteg7
    - &medusa age1rcf425yjzkua5keaktw6s9rkjwx28vgkjm7evtt0m5s3lpyz9p6sr73k6j
creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *phantasia
      - *gallifrey
      - *medusa
      pgp:
      - *christoph
