# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    ../common/optional/single-disk-encrypted.nix
    ../common/optional/ephemeral-btrfs.nix
  ];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s3.useDHCP = lib.mkDefault true;

  disko.devices.disk.${config.networking.hostName}.device = lib.mkForce "/dev/vda";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.graphics.enable = true;

  fileSystems."/persist/home/christoph/Documents/nix-config" = {
    fsType = "virtiofs";
    device = "nix-config";
    options = ["rw" "nofail" "uid=christoph" "gid=users"];
  };
}
